
package sv.unab.edu.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HolaMundoIntelliJ", targetNamespace = "http://webservice.unab.edu.sv/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HolaMundoIntelliJ {


    /**
     * 
     * @param nombre
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hola", targetNamespace = "http://webservice.unab.edu.sv/", className = "sv.unab.edu.ws.Hola")
    @ResponseWrapper(localName = "holaResponse", targetNamespace = "http://webservice.unab.edu.sv/", className = "sv.unab.edu.ws.HolaResponse")
    @Action(input = "http://webservice.unab.edu.sv/HolaMundoIntelliJ/holaRequest", output = "http://webservice.unab.edu.sv/HolaMundoIntelliJ/holaResponse")
    public String hola(
        @WebParam(name = "nombre", targetNamespace = "")
        String nombre);

    /**
     * 
     * @param nombre
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "adios", targetNamespace = "http://webservice.unab.edu.sv/", className = "sv.unab.edu.ws.Adios")
    @ResponseWrapper(localName = "adiosResponse", targetNamespace = "http://webservice.unab.edu.sv/", className = "sv.unab.edu.ws.AdiosResponse")
    @Action(input = "http://webservice.unab.edu.sv/HolaMundoIntelliJ/adiosRequest", output = "http://webservice.unab.edu.sv/HolaMundoIntelliJ/adiosResponse")
    public String adios(
        @WebParam(name = "nombre", targetNamespace = "")
        String nombre);

}
